# Generated by Django 4.1.7 on 2023-03-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("album", models.CharField(max_length=80)),
                ("writer", models.CharField(max_length=80)),
                ("rank", models.IntegerField()),
                ("year_release", models.IntegerField()),
                ("singer", models.CharField(max_length=80)),
                ("song_time", models.CharField(max_length=5)),
                ("spotify_streams", models.CharField(max_length=80)),
                ("rolling_stone_rank", models.IntegerField()),
                ("NME_rank", models.IntegerField()),
                ("UG_views", models.IntegerField()),
                ("UG_favourites", models.IntegerField()),
            ],
        ),
    ]
